import { defineStore } from 'pinia';
import morbidityLayer, { setMorbidityGeoIdSet, setMorbiditylayerStyle } from '@/libs/map/map-layer/morbidity-layer';
import { mapManager } from '@/libs/map/map-manager.js';
import { getMapLayerData } from '@/api/map-layer.js';
import { useProjectYearStore } from '@/store/project-year.js';
export const useMorbidityLayerStore = defineStore('morbidityLayer', {
    state: () => {
        return {
            layerList: [
                {
                    id: 'morbidity',
                    label: 'AQ Morbidity Risk',
                    children: [
                        {
                            id: 'morbidity_ERVR_PM25_Max_PercentRank',
                            label: 'ER visit-respiratory_PM2.5 (%ile)',
                            type: 'tile',
                            min: 0,
                            max: 100,
                            opacityValue: 75,
                            scaleValue: 3,
                            isCheck: true,
                            disabled: false,
                            children: [
                                {
                                    id: 'tile_100',
                                    label: '95 - 100 %ile',
                                    color: '#4040FF',
                                    min: 95,
                                    max: 100,
                                },
                                {
                                    id: 'tile_95',
                                    label: '90 - 95 %ile',
                                    color: '#405FEF',
                                    min: 90,
                                    max: 95,
                                },
                                {
                                    id: 'tile_90',
                                    label: '80 - 90 %ile',
                                    color: '#4080DF',
                                    min: 80,
                                    max: 90,
                                },
                                {
                                    id: 'tile_80',
                                    label: '70 - 80 %ile',
                                    color: '#409FCF',
                                    min: 70,
                                    max: 80,
                                },
                                {
                                    id: 'tile_70',
                                    label: '60 - 70 %ile',
                                    color: '#40BFBF',
                                    min: 60,
                                    max: 70,
                                },
                                {
                                    id: 'tile_60',
                                    label: '50 - 60 %ile',
                                    color: '#39DCAE',
                                    min: 50,
                                    max: 60,
                                },
                                {
                                    id: 'tile_50',
                                    label: '0 - 50 %ile',
                                    color: '#40FF9F',
                                    min: 0,
                                    max: 50,
                                },
                            ],
                        },
                        {
                            id: 'morbidity_ERVR_O3_Max_PercentRank',
                            label: 'ER visit-respiratory_O3 (%ile)',
                            min: 0,
                            max: 100,
                            type: 'tile',
                            opacityValue: 75,
                            scaleValue: 3,
                            isCheck: true,
                            disabled: false,
                            children: [
                                {
                                    id: 'tile_100',
                                    label: '95 - 100 %ile',
                                    color: '#4040FF',
                                    min: 95,
                                    max: 100,
                                },
                                {
                                    id: 'tile_95',
                                    label: '90 - 95 %ile',
                                    color: '#405FEF',
                                    min: 90,
                                    max: 95,
                                },
                                {
                                    id: 'tile_90',
                                    label: '80 - 90 %ile',
                                    color: '#4080DF',
                                    min: 80,
                                    max: 90,
                                },
                                {
                                    id: 'tile_80',
                                    label: '70 - 80 %ile',
                                    color: '#409FCF',
                                    min: 70,
                                    max: 80,
                                },
                                {
                                    id: 'tile_70',
                                    label: '60 - 70 %ile',
                                    color: '#40BFBF',
                                    min: 60,
                                    max: 70,
                                },
                                {
                                    id: 'tile_60',
                                    label: '50 - 60 %ile',
                                    color: '#39DCAE',
                                    min: 50,
                                    max: 60,
                                },
                                {
                                    id: 'tile_50',
                                    label: '0 - 50 %ile',
                                    color: '#40FF9F',
                                    min: 0,
                                    max: 50,
                                },
                            ],
                        },
                        {
                            id: 'morbidity_HAD_PM25_Max_PercentRank',
                            label: 'Hosp.Adm.-Youth-respiratory (%ile)',
                            min: 0,
                            max: 100,
                            type: 'tile',
                            opacityValue: 75,
                            scaleValue: 3,
                            isCheck: true,
                            disabled: false,
                            children: [
                                {
                                    id: 'tile_100',
                                    label: '95 - 100 %ile',
                                    color: '#4040FF',
                                    min: 95,
                                    max: 100,
                                },
                                {
                                    id: 'tile_95',
                                    label: '90 - 95 %ile',
                                    color: '#405FEF',
                                    min: 90,
                                    max: 95,
                                },
                                {
                                    id: 'tile_90',
                                    label: '80 - 90 %ile',
                                    color: '#4080DF',
                                    min: 80,
                                    max: 90,
                                },
                                {
                                    id: 'tile_80',
                                    label: '70 - 80 %ile',
                                    color: '#409FCF',
                                    min: 70,
                                    max: 80,
                                },
                                {
                                    id: 'tile_70',
                                    label: '60 - 70 %ile',
                                    color: '#40BFBF',
                                    min: 60,
                                    max: 70,
                                },
                                {
                                    id: 'tile_60',
                                    label: '50 - 60 %ile',
                                    color: '#39DCAE',
                                    min: 50,
                                    max: 60,
                                },
                                {
                                    id: 'tile_50',
                                    label: '0 - 50 %ile',
                                    color: '#40FF9F',
                                    min: 0,
                                    max: 50,
                                },
                            ],
                        },
                        {
                            id: 'morbidity_HAD_O3_Max_PercentRank',
                            label: 'Hosp.Adm.-Senior-respiratory (%ile)',
                            min: 0,
                            max: 100,
                            type: 'tile',
                            opacityValue: 75,
                            scaleValue: 3,
                            isCheck: true,
                            disabled: false,
                            children: [
                                {
                                    id: 'tile_100',
                                    label: '95 - 100 %ile',
                                    color: '#4040FF',
                                    min: 95,
                                    max: 100,
                                },
                                {
                                    id: 'tile_95',
                                    label: '90 - 95 %ile',
                                    color: '#405FEF',
                                    min: 90,
                                    max: 95,
                                },
                                {
                                    id: 'tile_90',
                                    label: '80 - 90 %ile',
                                    color: '#4080DF',
                                    min: 80,
                                    max: 90,
                                },
                                {
                                    id: 'tile_80',
                                    label: '70 - 80 %ile',
                                    color: '#409FCF',
                                    min: 70,
                                    max: 80,
                                },
                                {
                                    id: 'tile_70',
                                    label: '60 - 70 %ile',
                                    color: '#40BFBF',
                                    min: 60,
                                    max: 70,
                                },
                                {
                                    id: 'tile_60',
                                    label: '50 - 60 %ile',
                                    color: '#39DCAE',
                                    min: 50,
                                    max: 60,
                                },
                                {
                                    id: 'tile_50',
                                    label: '0 - 50 %ile',
                                    color: '#40FF9F',
                                    min: 0,
                                    max: 50,
                                },
                            ],
                        },
                        {
                            id: 'morbidity_SLD_O3_Max_PercentRank',
                            label: 'School loss days (%ile)',
                            min: 0,
                            max: 100,
                            type: 'tile',
                            opacityValue: 75,
                            scaleValue: 3,
                            isCheck: true,
                            disabled: false,
                            children: [
                                {
                                    id: 'tile_100',
                                    label: '95 - 100 %ile',
                                    color: '#4040FF',
                                    min: 95,
                                    max: 100,
                                },
                                {
                                    id: 'tile_95',
                                    label: '90 - 95 %ile',
                                    color: '#405FEF',
                                    min: 90,
                                    max: 95,
                                },
                                {
                                    id: 'tile_90',
                                    label: '80 - 90 %ile',
                                    color: '#4080DF',
                                    min: 80,
                                    max: 90,
                                },
                                {
                                    id: 'tile_80',
                                    label: '70 - 80 %ile',
                                    color: '#409FCF',
                                    min: 70,
                                    max: 80,
                                },
                                {
                                    id: 'tile_70',
                                    label: '60 - 70 %ile',
                                    color: '#40BFBF',
                                    min: 60,
                                    max: 70,
                                },
                                {
                                    id: 'tile_60',
                                    label: '50 - 60 %ile',
                                    color: '#39DCAE',
                                    min: 50,
                                    max: 60,
                                },
                                {
                                    id: 'tile_50',
                                    label: '0 - 50 %ile',
                                    color: '#40FF9F',
                                    min: 0,
                                    max: 50,
                                },
                            ],
                        },
                        {
                            id: 'morbidity_WLD_PM25_Max_PercentRank',
                            label: 'Work loss days (%ile)',
                            min: 0,
                            max: 100,
                            type: 'tile',
                            opacityValue: 75,
                            scaleValue: 3,
                            isCheck: true,
                            disabled: false,
                            children: [
                                {
                                    id: 'tile_100',
                                    label: '95 - 100 %ile',
                                    color: '#4040FF',
                                    min: 95,
                                    max: 100,
                                },
                                {
                                    id: 'tile_95',
                                    label: '90 - 95 %ile',
                                    color: '#405FEF',
                                    min: 90,
                                    max: 95,
                                },
                                {
                                    id: 'tile_90',
                                    label: '80 - 90 %ile',
                                    color: '#4080DF',
                                    min: 80,
                                    max: 90,
                                },
                                {
                                    id: 'tile_80',
                                    label: '70 - 80 %ile',
                                    color: '#409FCF',
                                    min: 70,
                                    max: 80,
                                },
                                {
                                    id: 'tile_70',
                                    label: '60 - 70 %ile',
                                    color: '#40BFBF',
                                    min: 60,
                                    max: 70,
                                },
                                {
                                    id: 'tile_60',
                                    label: '50 - 60 %ile',
                                    color: '#39DCAE',
                                    min: 50,
                                    max: 60,
                                },
                                {
                                    id: 'tile_50',
                                    label: '0 - 50 %ile',
                                    color: '#40FF9F',
                                    min: 0,
                                    max: 50,
                                },
                            ],
                        },
                        {
                            id: 'morbidity_AsthmaSymptoms_Max_PercentRank',
                            label: 'Asthma Cases max rate percentile (%ile)',
                            type: 'tile',
                            min: 0,
                            max: 100,
                            opacityValue: 75,
                            scaleValue: 3,
                            isCheck: true,
                            disabled: false,
                            children: [
                                {
                                    id: 'tile_100',
                                    label: '95 - 100 %ile',
                                    color: '#4040FF',
                                    min: 95,
                                    max: 100,
                                },
                                {
                                    id: 'tile_95',
                                    label: '90 - 95 %ile',
                                    color: '#405FEF',
                                    min: 90,
                                    max: 95,
                                },
                                {
                                    id: 'tile_90',
                                    label: '80 - 90 %ile',
                                    color: '#4080DF',
                                    min: 80,
                                    max: 90,
                                },
                                {
                                    id: 'tile_80',
                                    label: '70 - 80 %ile',
                                    color: '#409FCF',
                                    min: 70,
                                    max: 80,
                                },
                                {
                                    id: 'tile_70',
                                    label: '60 - 70 %ile',
                                    color: '#40BFBF',
                                    min: 60,
                                    max: 70,
                                },
                                {
                                    id: 'tile_60',
                                    label: '50 - 60 %ile',
                                    color: '#39DCAE',
                                    min: 50,
                                    max: 60,
                                },
                                {
                                    id: 'tile_50',
                                    label: '0 - 50 %ile',
                                    color: '#40FF9F',
                                    min: 0,
                                    max: 50,
                                },
                            ],
                        },
                        {
                            id: 'morbidity_ERVR_PM25_Max_Value',
                            label: 'ER visit-respiratory_PM2.5 (value)',
                            min: 0.4,
                            max: 59.2,
                            type: 'value',
                            opacityValue: 75,
                            scaleValue: 3,
                            isCheck: true,
                            disabled: false,
                            children: [
                                {
                                    id: 'value_59',
                                    label: '50.8 - 59.2',
                                    color: '#4040FF',
                                    min: 50.8,
                                    max: 59.2,
                                },
                                {
                                    id: 'value_50',
                                    label: '42.4 - 50.8',
                                    color: '#405FEF',
                                    min: 42.4,
                                    max: 50.8,
                                },
                                {
                                    id: 'value_42',
                                    label: '34 - 42.4',
                                    color: '#4080DF',
                                    min: 34,
                                    max: 42.4,
                                },
                                {
                                    id: 'value_34',
                                    label: '25.6 - 34',
                                    color: '#409FCF',
                                    min: 25.6,
                                    max: 34,
                                },
                                {
                                    id: 'value_25',
                                    label: '17.2 - 25.6',
                                    color: '#40BFBF',
                                    min: 17.2,
                                    max: 25.6,
                                },
                                {
                                    id: 'value_17',
                                    label: '8.8 - 17.2',
                                    color: '#39DCAE',
                                    min: 8.8,
                                    max: 17.2,
                                },
                                {
                                    id: 'value_8',
                                    label: '0.4 - 8.8',
                                    color: '#40FF9F',
                                    min: 0.4,
                                    max: 8.8,
                                },
                            ],
                        },
                        {
                            id: 'morbidity_ERVR_O3_Max_Value',
                            label: 'ER visit-respiratory_O3 (value)',
                            min: 0.4,
                            max: 59.2,
                            type: 'value',
                            opacityValue: 75,
                            scaleValue: 3,
                            isCheck: true,
                            disabled: false,
                            children: [
                                {
                                    id: 'value_59',
                                    label: '50.8 - 59.2',
                                    color: '#4040FF',
                                    min: 50.8,
                                    max: 59.2,
                                },
                                {
                                    id: 'value_50',
                                    label: '42.4 - 50.8',
                                    color: '#405FEF',
                                    min: 42.4,
                                    max: 50.8,
                                },
                                {
                                    id: 'value_42',
                                    label: '34 - 42.4',
                                    color: '#4080DF',
                                    min: 34,
                                    max: 42.4,
                                },
                                {
                                    id: 'value_34',
                                    label: '25.6 - 34',
                                    color: '#409FCF',
                                    min: 25.6,
                                    max: 34,
                                },
                                {
                                    id: 'value_25',
                                    label: '17.2 - 25.6',
                                    color: '#40BFBF',
                                    min: 17.2,
                                    max: 25.6,
                                },
                                {
                                    id: 'value_17',
                                    label: '8.8 - 17.2',
                                    color: '#39DCAE',
                                    min: 8.8,
                                    max: 17.2,
                                },
                                {
                                    id: 'value_8',
                                    label: '0.4 - 8.8',
                                    color: '#40FF9F',
                                    min: 0.4,
                                    max: 8.8,
                                },
                            ],
                        },
                        {
                            id: 'morbidity_HAD_PM25_Max_Value',
                            label: 'Hosp.Adm.-Youth-respiratory (value)',
                            min: -0.1,
                            max: 17.4,
                            type: 'value',
                            opacityValue: 75,
                            scaleValue: 3,
                            isCheck: true,
                            disabled: false,
                            children: [
                                {
                                    id: 'value_17',
                                    label: '14.9 - 17.4',
                                    color: '#4040FF',
                                    min: 14.9,
                                    max: 17.4,
                                },
                                {
                                    id: 'value_14',
                                    label: '12.4 - 14.9',
                                    color: '#405FEF',
                                    min: 12.4,
                                    max: 14.9,
                                },
                                {
                                    id: 'value_12',
                                    label: '9.9 - 12.4',
                                    color: '#4080DF',
                                    min: 9.9,
                                    max: 12.4,
                                },
                                {
                                    id: 'value_9',
                                    label: '7.4 - 9.9',
                                    color: '#409FCF',
                                    min: 7.4,
                                    max: 9.9,
                                },
                                {
                                    id: 'value_7',
                                    label: '4.9 - 7.4',
                                    color: '#40BFBF',
                                    min: 4.9,
                                    max: 7.4,
                                },
                                {
                                    id: 'value_4',
                                    label: '2.4 - 4.9',
                                    color: '#39DCAE',
                                    min: 2.4,
                                    max: 4.9,
                                },
                                {
                                    id: 'value_2',
                                    label: '-0.1 - 2.4',
                                    color: '#40FF9F',
                                    min: -0.1,
                                    max: 2.4,
                                },
                            ],
                        },
                        {
                            id: 'morbidity_HAD_O3_Max_Value',
                            label: 'Hosp.Adm.-Senior-respiratory (value)',
                            min: -0.1,
                            max: 7.3,
                            type: 'value',
                            opacityValue: 75,
                            scaleValue: 3,
                            isCheck: true,
                            disabled: false,
                            children: [
                                {
                                    id: 'value_7',
                                    label: '6.5 - 7.3',
                                    color: '#4040FF',
                                    min: 6.5,
                                    max: 7.3,
                                },
                                {
                                    id: 'value_6',
                                    label: '5.4 - 6.5',
                                    color: '#405FEF',
                                    min: 5.4,
                                    max: 6.5,
                                },
                                {
                                    id: 'value_5',
                                    label: '4.3 - 5.4',
                                    color: '#4080DF',
                                    min: 4.3,
                                    max: 5.4,
                                },
                                {
                                    id: 'value_4',
                                    label: '3.2 - 4.3',
                                    color: '#409FCF',
                                    min: 3.2,
                                    max: 4.3,
                                },
                                {
                                    id: 'value_3',
                                    label: '2.1 - 3.2',
                                    color: '#40BFBF',
                                    min: 2.1,
                                    max: 3.2,
                                },
                                {
                                    id: 'value_2',
                                    label: '1 - 2.1',
                                    color: '#39DCAE',
                                    min: 1,
                                    max: 2.1,
                                },
                                {
                                    id: 'value_1',
                                    label: '-0.1 - 1',
                                    color: '#40FF9F',
                                    min: -0.1,
                                    max: 1,
                                },
                            ],
                        },
                        {
                            id: 'morbidity_SLD_O3_Max_Value',
                            label: 'School loss days (value)',
                            min: -0.1,
                            max: 11198.1,
                            type: 'value',
                            opacityValue: 75,
                            scaleValue: 3,
                            isCheck: true,
                            disabled: false,
                            children: [
                                {
                                    id: 'value_11198',
                                    label: '9598.1 - 11198.1',
                                    color: '#4040FF',
                                    min: 9598.1,
                                    max: 11198.1,
                                },
                                {
                                    id: 'value_9598',
                                    label: '7998.4 - 9598.1',
                                    color: '#405FEF',
                                    min: 7998.4,
                                    max: 9598.1,
                                },
                                {
                                    id: 'value_7998',
                                    label: '6398.7 - 7998.4',
                                    color: '#4080DF',
                                    min: 6398.7,
                                    max: 7998.4,
                                },
                                {
                                    id: 'value_6398',
                                    label: '4799 - 6398.7',
                                    color: '#409FCF',
                                    min: 4799,
                                    max: 6398.7,
                                },
                                {
                                    id: 'value_4799',
                                    label: '3199.3 - 4799',
                                    color: '#40BFBF',
                                    min: 3199.3,
                                    max: 4799,
                                },
                                {
                                    id: 'value_3199',
                                    label: '1599.6 - 3199.3',
                                    color: '#39DCAE',
                                    min: 1599.6,
                                    max: 3199.3,
                                },
                                {
                                    id: 'value_1599',
                                    label: '-0.1 - 1599.6',
                                    color: '#40FF9F',
                                    min: -0.1,
                                    max: 1599.6,
                                },
                            ],
                        },
                        {
                            id: 'morbidity_WLD_PM25_Max_Value',
                            label: 'Work loss days (value)',
                            min: -0.1,
                            max: 2158.3,
                            type: 'value',
                            opacityValue: 75,
                            scaleValue: 3,
                            isCheck: true,
                            disabled: false,
                            children: [
                                {
                                    id: 'value_2158',
                                    label: '1849.7 - 2158.3',
                                    color: '#4040FF',
                                    min: 1849.7,
                                    max: 2158.3,
                                },
                                {
                                    id: 'value_1849',
                                    label: '1541.4 - 1849.7',
                                    color: '#405FEF',
                                    min: 1541.4,
                                    max: 1849.7,
                                },
                                {
                                    id: 'value_1541',
                                    label: '1233.1 - 1541.4',
                                    color: '#4080DF',
                                    min: 1233.1,
                                    max: 1541.4,
                                },
                                {
                                    id: 'value_1233',
                                    label: '924.8 - 1233.1',
                                    color: '#409FCF',
                                    min: 924.8,
                                    max: 1233.1,
                                },
                                {
                                    id: 'value_924',
                                    label: '616.5 - 924.8',
                                    color: '#40BFBF',
                                    min: 616.5,
                                    max: 924.8,
                                },
                                {
                                    id: 'value_616',
                                    label: '308.2 - 616.5',
                                    color: '#39DCAE',
                                    min: 308.2,
                                    max: 616.5,
                                },
                                {
                                    id: 'value_308',
                                    label: '-0.1 - 308.2',
                                    color: '#40FF9F',
                                    min: -0.1,
                                    max: 308.2,
                                },
                            ],
                        },
                        {
                            id: 'morbidity_AsthmaSymptoms_Max_Value',
                            label: 'Asthma Cases (value)',
                            min: 0,
                            max: 29000,
                            type: 'value',
                            opacityValue: 75,
                            scaleValue: 3,
                            isCheck: true,
                            disabled: false,
                            children: [
                                {
                                    id: 'value_2158',
                                    label: '24857.14 - 29000',
                                    color: '#4040FF',
                                    min: 24857.14,
                                    max: 29000,
                                },
                                {
                                    id: 'value_1849',
                                    label: '20714.28 - 24857.14',
                                    color: '#405FEF',
                                    min: 20714.28,
                                    max: 24857.14,
                                },
                                {
                                    id: 'value_1541',
                                    label: '16571.42 - 20714.28',
                                    color: '#4080DF',
                                    min: 16571.42,
                                    max: 20714.28,
                                },
                                {
                                    id: 'value_1233',
                                    label: '12428.56 - 16571.42',
                                    color: '#409FCF',
                                    min: 12428.56,
                                    max: 16571.42,
                                },
                                {
                                    id: 'value_924',
                                    label: '8285.7 - 12428.56',
                                    color: '#40BFBF',
                                    min: 8285.7,
                                    max: 12428.56,
                                },
                                {
                                    id: 'value_616',
                                    label: '4142.84 - 8285.7',
                                    color: '#39DCAE',
                                    min: 4142.84,
                                    max: 8285.7,
                                },
                                {
                                    id: 'value_308',
                                    label: '0 - 4142.84',
                                    color: '#40FF9F',
                                    min: 0,
                                    max: 4142.84,
                                },
                            ],
                        },
                    ],
                },
            ],
            checkList: [],
            dicKey: {
                morbidity_ERVR_PM25_Max_PercentRank: 'Morbidity_ERVR_PM25',
                morbidity_ERVR_O3_Max_PercentRank: 'Morbidity_ERVR_O3',
                morbidity_HAD_PM25_Max_PercentRank: 'Morbidity_HAD_PM25',
                morbidity_HAD_O3_Max_PercentRank: 'Morbidity_HAD_O3',
                morbidity_SLD_O3_Max_PercentRank: 'Morbidity_SLD_O3',
                morbidity_WLD_PM25_Max_PercentRank: 'Morbidity_WLD_PM25',
                morbidity_ERVR_PM25_Max_Value: 'Morbidity_ERVR_PM25',
                morbidity_ERVR_O3_Max_Value: 'Morbidity_ERVR_O3',
                morbidity_HAD_PM25_Max_Value: 'Morbidity_HAD_PM25',
                morbidity_HAD_O3_Max_Value: 'Morbidity_HAD_O3',
                morbidity_SLD_O3_Max_Value: 'Morbidity_SLD_O3',
                morbidity_WLD_PM25_Max_Value: 'Morbidity_WLD_PM25',
                morbidity_AsthmaSymptoms_Max_PercentRank: 'AsthmaSymptoms',
                morbidity_AsthmaSymptoms_Max_Value: 'AsthmaSymptoms',
            },
        };
    },
    actions: {
        init() {
            this.checkList = [];
            setMorbidityGeoIdSet({}, '');
        },
        handleWatcher() {
            if (this.checkList.length) {
                setMorbiditylayerStyle();
            }
        },
        async handleLayerChange() {
            const mapIns = mapManager.getMapIns();
            let layers = mapIns.getAllLayers();
            let layerIndex = layers.findIndex((item) => item === morbidityLayer);
            if (this.checkList.length) {
                if (layerIndex === -1) {
                    mapIns.addLayer(morbidityLayer);
                }
                const projectYearStore = useProjectYearStore();
                let key = this.checkList[0];
                let params = {
                    pollutantType: this.dicKey[key],
                    dataType: key.includes('PercentRank') ? 'PercentRank' : 'value',
                    year: projectYearStore.projectYear,
                    dataScaleType: 'County',
                };
                let result = await getMapLayerData(params);
                setMorbidityGeoIdSet(result, key);
            } else {
                setMorbidityGeoIdSet({}, '');
                if (layerIndex !== -1) {
                    mapIns.removeLayer(morbidityLayer);
                }
            }
        },
    },
});
