export const versionList = [
    {
        version: '1.4.28',
        date: '2025-10-17',
        updates: [
            "Under 'Reset' tab: remove the percentile options from appearing under 'Set all to risk-based default value and remove 'Set all to risk-based desired %ile' in the normal version and add it to the advanced option ",
            "Rename 'Help' to 'User Manual'. Link to the new user manual provided by the TOCOR ",
            "Under the proximity analysis, 'Create Individual Sites Table' and 'Summary Table' are repetitive. Remove the 'Summary Table' option.",
            "Under proximity analysis, 'Clear' and 'Reset' do the same thing. Remove 'Reset' and retain 'Clear'.",
            "NO2 satellite data should be removed everywhere, including in the information panel on the left and in the data panel",
            "Un-indent the text in the 'Advanced Option' pop out box",
            'In "Chossing a data scale" box in the quick start guide, please change the text to read: "The top left panel allows you to switch between county and census tract-level data. Changes to the year of the data can be made where applicable. See the user manual for more information."',
            'Under "Configure Cirlce Bar" remove everything under "title" and only maintain opacity ',
            'In the top bar in the Map Layer drop down, "Age Demographics" should be removed from the Nexus Metrics option'
        ],
        bugs: [],
    },
    {
        version: '1.4.27',
        date: '2025-09-27',
        updates: [
            'Changed "Demographics" to "Age Demographics"',
            'Update the data year',
        ],
        bugs: [],
    },
    {
        version: '1.4.26',
        date: '2025-09-19',
        updates: [
            'Fixed the misspelling of "Emissions" in "Source/Sector Emissions: United States" for "Emissions Chart" (removed the extra "S").',
            'Corrected spelling errors in the CBSA dropdown: changed "Ca?on City" to "Cañon City" and "Espa?ola" to "Española" (resolved accent mark display issue).',
            'When "Age Demographics Indicator" is clicked: 1. Updated the map legend to "Age Demographics". 2.Modified the left panel text from "Demographics" to "Age Demographics".',
            'Updated the data sources and web links table to match current data in the tool (e.g., removed NO₂ satellite data and heat index; added age demographics from Census).',
            'Added a blue question mark in the "Air Toxics" section on the lefthand panel'
        ],
        bugs: [],
    },
    {
        version: '1.4.25',
        date: '2025-08-30',
        updates: [
            'Proximity Analysis - add the age demographic information ("Under 5 Years" and "62 Years and Older" only) back into the Individual Sites Table, Summary Table, and the Proximity Analysis Output Table.',
            'The Attribute Table needs to support filtering capabilities for the "Under 5 Years" and "62 Years and Older" fields.'
        ],
        bugs: [],
    },
    {
        version: '1.4.24',
        date: '2025-08-07',
        updates: [
            'Supplementarily import the missing census tracts into the data database.',
            'Proximity Analysis - change “Select tracts around locations” to “Select tracts around location(s)”.',
            'Proximity Analysis - for a given Location type, update the options box header text for the left box',
            'Proximity Analysis - change “Monitoring Sites by map” to “Monitoring Sites on map” and change “Facilities by map” to “Facilities on map”',
            'Proximity Analysis - remove AirToxScreen Risk threshold button from proximity analysis',
            'Proximity Analysis - the individual sites table still have demographics information in it. Remove these demographics',
            'Proximity Analysis - remove the "Output" button from the "Individual sites table"',
            'Monitoring Site module - change “Monitor Sites Table” to “Monitoring Sites”',
            'Monitoring Site and Emissions module - if no area is selected, have the “Emission Sources” and “Monitor Sites” say “Source/Sector Emissions: United States” and “Monitor Sites: United States”, respectively',
            'Map Layer - display the demographics information as a percentage, not a percentile',
            'May Layer - remove the Annual averages satellite NO2 option from the AQ Concentration',
        ],
        bugs: ['fix bug: When selecting an EPA Region or a CBSA area, all color blocks disappear.'],
    },
    {
        version: '1.4.23',
        date: '2025-07-25',
        updates: ['Update dependency package versions', 'Optimize export Excel function', 'Enhance data processing logic'],
        bugs: [],
    },
    {
        version: '1.4.22',
        date: '2025-07-22',
        updates: ['Update: Cancer Risk Layer Legend'],
        bugs: [],
    },
    {
        version: '1.4.21',
        date: '2025-07-14',
        updates: [
            'Change“Indicator(2023)”to“Indicator (2023)". (Add a space.)',
            'Change“Top Risk Percentile”to“Percentage”under the Demographics section on the left-hand panel.',
            'Add demographics information to the attribute table (i.e., the age demographics information).',
            'Under the Proximity Analysis, change“localtions” to“locations”.',
        ],
        bugs: [],
    },
    {
        version: '1.4.20',
        date: '2025-07-09',
        updates: ['Add a control to show the current zoom level on the map', 'Update: Proximity Analysis Main Page'],
        bugs: [],
    },
    {
        version: '1.4.19',
        date: '2025-06-30',
        updates: ['Update: Demographics Add question mark to the right of the title', 'Update: Proximity Analysis Main Page'],
        bugs: [],
    },
    {
        version: '1.4.18',
        date: '2025-05-14',
        updates: ['Update: BenMAP County level data'],
        bugs: [],
    },
    {
        version: '1.4.17',
        date: '2025-04-23',
        updates: ['Update: Census Data-Adding Age Demographics'],
        bugs: [],
    },
    {
        version: '1.4.16',
        date: '2025-04-14',
        updates: ['Add the advanced options'],
        bugs: ['Fix the bug of the map layer display blur'],
    },
    {
        version: '1.4.15',
        date: '2025-04-10',
        updates: ['Remove heat index from the tool everywhere', 'Updates to the left hand panel', 'Update magnifying glass icon', 'Minor text edits'],
        bugs: [],
    },
    {
        version: '1.4.14',
        date: '2025-03-28',
        updates: ['add different icon representations for each pollutant monitoring site'],
        bugs: [],
    },
    {
        version: '1.4.13',
        date: '2025-03-15',
        updates: [
            'Change source emission and monitor legends',
            'Decrease scrolling sensitivity',
            'Changing Meterology sites to display the common location name rather than site ID',
            'Update the language for air toxics data',
            'For Monitor Sites: Remove "Include Monitor Year Since" and "Monitor Ranking Year" and add one option title "Monitor Year:"',
        ],
        bugs: [],
    },
    {
        version: '1.4.12',
        date: '2025-03-07',
        updates: ['Adding a Quick Start Guide'],
        bugs: [],
    },
    {
        version: '1.4.11',
        date: '2025-02-28',
        updates: ['Optimize the display of the map layer', 'Optimize the display of the summary plot', 'Optimize the display of the summary table'],
        bugs: [],
    },
    {
        version: '1.4.10',
        date: '2025-02-19',
        updates: ['Finish updating to the 2020 data from AirToxScreen and BenMAP', 'Add units to all tables and charts in the tool', 'Remove the project year'],
        bugs: [],
    },
    {
        version: '1.4.9',
        date: '2025-02-12',
        updates: ['Optimize page interactions', 'Optimize some copywriting expressions'],
        bugs: [],
    },
    {
        version: '1.4.8',
        date: '2025-02-06',
        updates: ['Hide data input files module'],
        bugs: [],
    },
    {
        version: '1.4.7',
        date: '2025-02-05',
        updates: [
            'Add login verification function',
            'Modify the default map layer',
            'Separate“AQ Mortality Risk & Air Toxics Cancer Risk" into“AQ Mortality Risk" and “Air Toxics Cancer Risk"',
            'Modified Copy Showcase',
        ],
        bugs: [],
    },
    {
        version: '1.4.6',
        date: '2024-07-25',
        updates: ['AirToxic label is changed from “Cancer Risk” to “Maximum Block-level Cancer Risk”.', 'AirToxic Data had be updated with “2020”.'],
        bugs: [],
    },
    {
        version: '1.4.5',
        date: '2024-07-19',
        updates: ['Import 2020 airtoxic cancer risk data'],
        bugs: [],
    },
    {
        version: '1.4.4',
        date: '2024-06-17',
        updates: ['Optimise the function display on the left sidebar'],
        bugs: [],
    },
    {
        version: '1.4.3',
        date: '2024-06-12',
        updates: ['Remove right click display and clear functions', 'Add a clear all function', 'Add a reset default function'],
        bugs: [],
    },
    {
        version: '1.4.2',
        date: '2024-06-07',
        updates: ['Set new step for nocancer HI'],
        bugs: [],
    },
    {
        version: '1.4.1',
        date: '2024-05-29',
        updates: ['Optimising the presentation of summary plots', 'Optimising the display of the map layer'],
        bugs: [],
    },
    {
        version: '1.4',
        date: '2024-05-24',
        updates: ['Update current page style'],
        bugs: [],
    },
    {
        version: '1.3',
        date: '2024-04-26',
        updates: ['Add hints for important fields', 'Adjust the default font of the page'],
        bugs: [],
    },
    {
        version: '1.2',
        date: '2023-11-09',
        updates: ['Updated Quick Start Guide', 'Add a layer about Top 10-day average O3 in the Map Layer'],
        bugs: [],
    },
    {
        version: '1.1',
        date: '2023-10-09',
        updates: ['Fix the bug about CBSA layer display blur', 'Optimize system interaction'],
        bugs: [],
    },
    {
        version: '1.0',
        date: '2023-08-25',
        updates: ['Optimize page performance', 'Unified export xlsx file styles'],
        bugs: [],
    },
    {
        version: '0.6',
        date: '2023-08-16',
        updates: ['Support to export emission sources/monitor sites table', 'Optimize the module of Proximity Analysis', 'Optimize the module of Map Layer'],
        bugs: [],
    },
    {
        version: '0.5',
        date: '2023-08-08',
        updates: ['Develop the function of "Display CBSA Risk Ranking"', 'Develop the module of Map Layer', 'Develop the  module of Summary Plot'],
        bugs: [],
    },
    {
        version: '0.4',
        date: '2023-07-21',
        updates: [
            'Develop the function of "MP Risk Ranking"',
            'Include a "Zoom to" and "Pan" menu on the top of detailed information window. ',
            'Develop the function of the way to show in the module of Proximity Analysis',
            'Develop the function to select a group of census tracts by custom shape in the module of Proximity Analysis',
        ],
        bugs: [],
    },
    {
        version: '0.3',
        date: '2023-07-03',
        updates: [
            'Develop a new module of Map Layer',
            'Develop a new module of Proximity Analysis',
            'Develop a new module of Summary Table',
            'Develop a new module of Individual Sites Table',
        ],
        bugs: [],
    },
    {
        version: '0.2',
        date: '2023-06-13',
        updates: [
            'Develop a new module of Major Emission Sources',
            'Develop a new module of Configure Circle Color Bar to change map colors',
            'Develop a new module of Meteorological Site',
            'Develop a new module of Date Input',
            'Add  filters on the "View Current Data" page',
        ],
        bugs: [],
    },
    {
        version: '0.1',
        date: '2023-06-05',
        updates: [
            'New design for NEXUS web prototype',
            'Include 2017~2019 risk data',
            'Support both County and Census tract level data display',
            'Include Heat Index data',
            'Develop a new module of View Current Data',
            'Develop a new module of Quick Start Guide',
            'Develop a new function of Monitor Sites',
            'Developed a new module of Data Sources',
        ],
        bugs: [],
    },
];
